package com.techvvs.inventory.service.tenant.constants;


public enum TenantIndustry {

    CANNABIS_RETAIL,
    CANNABIS_WHOLESALE,
    CANNABIS_DELIVERY,
    CANNABIS_CULTIVATION,
    CANNABIS_TRANSPORT,
    CANNABIS_MANUFACTURING,
    ALCOHOL_RETAIL,
    ALCOHOL_WHOLESALE,
    CLOTHING,
    FOOD,
    NON_TANGIBLE_SERVICES,
    CONVENIENCE_STORE,
    BOOKS,
    SMOKE_SHOP,
    POP_UP,
    HEALTH_WELLNESS,
    AUTO_SHOP,
    GENERAL_WHOLESALE_B2B,
    OTHER_TANGIBLE_GOODS,
    SALON_SERVICES,
    TRADE_SERVICES,
    TRAVEL_SERVICES,
    ENTERTAINMENT_SERVICES,
    PET_SERVICES

}
